run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gofmt
    - goimports
    - lll

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gofmt:
    simplify: true
  errcheck:
    check-type-assertions: true
  staticcheck:
    checks: ["all"]
