services:

  db:
    container_name: avito-postgres
    image: postgres:17
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  shop:
    container_name: avito-shop
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    command: ./bucket-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy